//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Solicitud
    {
        public int codigo { get; set; }
        public int codSolicitante { get; set; }
        public int deptoDestino { get; set; }
        public System.DateTime fechaCreacion { get; set; }
        public string detalleSolicitud { get; set; }
        public int codAsignado { get; set; }
        public System.DateTime fechaCierre { get; set; }
        public int estadoSolicitud { get; set; }
        public string DetalleCierreSolicitud { get; set; }
    }
}
