//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class solicitudes_vista
    {
        public int Solicitud { get; set; }
        public string Departamento { get; set; }
        public string Solicitante { get; set; }
        public System.DateTime Creacion { get; set; }
        public string Detalle { get; set; }
        public string Estado { get; set; }
        public int codSolicitante { get; set; }
        public int deptoDestino { get; set; }
        public int codAsignado { get; set; }
        public int estadoSolicitud { get; set; }
    }
}
