//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HelpDeskDB
{
    using System;
    using System.Collections.Generic;
    
    public partial class Usuarios
    {
        public int Codigo { get; set; }
        public int CodPersona { get; set; }
        public string Usuario { get; set; }
        public string Pass { get; set; }
        public Nullable<int> IdPerfil { get; set; }
        public Nullable<int> estado { get; set; }
    
        public virtual Perfiles Perfiles { get; set; }
        public virtual Persona Persona { get; set; }
    }
}
